# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: "SHA256:33FcoA0wB92jAyfVDKdsu0GxdwcpsqcqAMmRWWm6CKM jsimpson@MacBook-Pro.fritz.box"
    sshKeySecureFile: "ado"
    sshPublicKey: "foo bar not real"

- script: |
    git config user.name "Julian Simpson"
    git config user.email "simpsonjulian@gmail.com"
    git remote add github git@github.com:simpsonjulian/TestingProject.git
    ssh-keyscan github.com
    git push github --all
  displayName: 'Run a multi-line script'
