# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    git config user.name "Julian Simpson"
    git config user.email "simpsonjulian@gmail.com"
    git remote add github https://github.com/simpsonjulian/TestingProject.git
    git push -u github main
  displayName: 'Run a multi-line script'
